name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Bot khusus yang beneran ngerender karakter Pacman & Hantu asli
      - name: GitHub Readme Pacman
        uses: jayphelps/github-readme-pacman@v1.2.0
        with:
          github_user_name: patihpyyt
          output: dist/github-readme-pacman.gif

      - name: Push Pacman GIF to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
