name: Generate arcade animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1. Langkah wajib biar robot bisa akses repositori lu
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Bikin folder penampung secara otomatis biar robotnya gak crash
      - name: Create output directory
        run: mkdir -p github-contribution-wall

      # 3. Jalankan generator Pacman murni bawaan temen lu
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: patihpyyt
          games: 'pacman'

      # 4. Push hasilnya ke branch khusus pacman-output
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: github-contribution-wall
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
